//
//  AMBACommands.h
//  Madv360_v1
//
//  Created by 张巧隔 on 16/8/9.
//  Copyright © 2016年 Cyllenge. All rights reserved.
//

#ifndef AMBACommands_h
#define AMBACommands_h

//回话标识
#define AMBA_SESSION_TOKEN_INIT 0
#define AMBA_SESSION_TOKEN AMBA_SESSION_TOKEN_INIT

//成功标识
#define AMBA_COMMAND_OK 0
#define AMBA_NOTIFICATION_OK 0x80

#define AMBA_RVAL_START_SESSION_DENIED -3

#define SSID_TAG @"AP_SSID="
#define PASSWORD_TAG @"AP_PASSWD="
#define APPUBLIC_TAG @"AP_PUBLIC="
#define BACKSLASH_PATH_HEAD_TAG @"C:"
#define SLASH_PATH_HEAD_TAG @"/tmp/SD0"

//JPEG缩略图
#define GET_THUMB_TYPE_THUMB @"thumb"
//JPEG全图
#define GET_THUMB_TYPE_FULLVIEW @"fullview"
//H.264的第一帧数据
#define GET_THUMB_TYPE_IDR @"idr"
#define GET_FILE_COMPLETE_TYPE @"get_file_complete"
#define GET_FILE_FAILED_TYPE @"get_file_failed"
#define PUT_FILE_COMPLETE_TYPE @"put_file_complete"
#define PUT_FILE_FAIL_TYPE @"put_file_fail"

#define GET_STORAGE_TYPE_FREE @"free"
#define GET_STORAGE_TYPE_TOTAL @"total"

//实时预览流
#define AMBA_CAMERA_RTSP_URL_ROOT @"rtsp://192.168.42.1"
#define AMBA_CAMERA_RTSP_LIVE_URL AMBA_CAMERA_RTSP_URL_ROOT@"/live"
#define RTSP_URL_SCHEME @"rtsp://"
#define RTMP_URL_SCHEME @"rtmp://"
// HTTP下载地址
#define HTTP_DOWNLOAD_URL_PREFIX @"http://192.168.42.1:50422"
#define HTTP_DOWNLOAD_REMOTE_ROOT @"/tmp/SD0/DCIM"

//相机IP地址
#define AMBA_CAMERA_IP @"192.168.42.1"
//相机命令端口
#define AMBA_CAMERA_COMMAND_PORT 7878
//相机数据端口
#define AMBA_CAMERA_DATA_PORT 8787
//socket超时时间
#define AMBA_CAMERA_TIMEOUT 5 * 1000
//会话类型
#define AMBA_SESSION_TYPE @"TCP"
//查询会话
#define AMBA_MSGID_QUERY_SESSION_HOLDER 1793
//启动会话命令ID
#define AMBA_MSGID_START_SESSION 257
//关闭会话命令ID
#define AMBA_MSGID_STOP_SESSION 258
#define AMBA_MSGID_RESET_VF 259
#define AMBA_MSGID_STOP_VF 260
//设置客户端信息命令ID
#define AMBA_MSGID_SET_CLNT_INFO 261
//获取缩略图命令ID
#define AMBA_MSGID_GET_THUMB 1025
//重启WiFi
#define AMBA_MSGID_WIFI_RESTART 1537
//设置WiFi信息
#define AMBA_MSGID_SET_WIFI_SETTING 1538
//获取WiFi设置信息
#define AMBA_MSGID_GET_WIFI_SETTING 1539
//关闭WiFi
#define AMBA_MSGID_WIFI_STOP 1540
//启动WiFi
#define AMBA_MSGID_WIFI_START 1541
//获取WiFi状态
#define AMBA_MSGID_GET_WIFI_STATUS 1542
#define AMBA_MSGID_SET_PHOTO_MODE 2307
#define AMBA_MSGID_SET_VIDEO_MODE 2308

//开始常规录像命令
#define AMBA_MSGID_START_VIDEO_NORMAL 513
//停止录像命令
#define AMBA_MSGID_STOP_VIDEO 514
//获取录像时间ID
#define AMBA_MSGID_GET_RECORD_TIME 515

//常规拍照
#define AMBA_MSGID_SHOOT_PHOTO_NORMAL 0x1300
//拍照命令ID ??
#define AMBA_MSGID_TAKE_PHOTO 769

//秒拍摄影设置
#define AMBA_MSGID_SET_VIDEO_MICRO_PARAM 0x120A
//开始秒拍摄影
#define AMBA_MSGID_START_VIDEO_MICRO 0x120C
//延时摄影设置
#define AMBA_MSGID_SET_VIDEO_TIMELAPSE_PARAM 0x120D
//开始延时摄影
#define AMBA_MSGID_START_VIDEO_TIMELAPSE 0x120F

//定时拍照设置
#define AMBA_MSGID_SET_PHOTO_TIMING_PARAM 0x1302
//开始定时拍照
#define AMBA_MSGID_SHOOT_PHOTO_TIMING 0x1304
//间隔拍照设置
#define AMBA_MSGID_SET_PHOTO_INTERVAL_PARAM 0x1341
//开始间隔拍照 0x13A1
#define AMBA_MSGID_SHOOT_PHOTO_INTERVAL  5025
//连续拍照设置 4915
#define AMBA_MSGID_SET_PHOTO_CONTINUOUS_PARAM  0x1333
//开始连续拍照 5027
#define AMBA_MSGID_SHOOT_PHOTO_CONTINUOUS  0x13A3
//慢动作设置
#define AMBA_MSGID_SET_VIDEO_SLOWMOTION_PARAM 0x1334
//开始慢动作摄影 0x13A4
#define AMBA_MSGID_START_VIDEO_SLOWMOTION  5028

//循环录制失败
#define AMBA_MSGID_START_LOOP_FAIL  0x1212

#define AMBA_MSGID_SAVE_VIDEO_DONE 0x2000
#define AMBA_MSGID_SAVE_PHOTO_DONE 0x2001
#define AMBA_MSGID_MP4_FILE_SPLIT_DONE 0x2003

#define AMBA_MSGID_GET_FILE 1285
#define AMBA_MSGID_PUT_FILE 1286

#define AMBA_MSGID_CANCEL_FILE_TRANSFER 1287

#define AMBA_MSGID_FILE_TRANSFER_RESULT 7
#define AMBA_MSGID_UPDATE_FIRMWARE 8

#define AMBA_MSGID_CD 1283
#define AMBA_MSGID_LS 1282

#define AMBA_MSGID_RTC_SYNC 0x1803

//设置GPS信息
#define AMBA_MSGID_SET_GPS_INFO  4917

#define AMBA_MSGID_SET_CAMERA_MODE 0x1203
#define AMBA_PARAM_CAMERA_MODE_VIDEO  0
#define AMBA_PARAM_CAMERA_MODE_PHOTO 1

#define AMBA_MSGID_SET_VIDEO_FILTER 0x1201

#define AMBA_MSGID_SET_WHITEBALANCE 0x1401
#define AMBA_PARAM_WHITEBALANCE_AUTO 0
#define AMBA_PARAM_WHITEBALANCE_OUTDOOR 1
#define AMBA_PARAM_WHITEBALANCE_SHADOW 2
#define AMBA_PARAM_WHITEBALANCE_CLOUDY 3
#define AMBA_PARAM_WHITEBALANCE_NIGHT 4

#define AMBA_MSGID_SET_ISO 0x1406

#define AMBA_MSGID_SET_SHUTTER 0x1407

#define AMBA_MSGID_FORMAT_SD 0x4

#define AMBA_MSGID_GET_SN 0x1001

#define AMBA_MSGID_GET_VENDOR 0x1002

#define AMBA_MSGID_GET_DEVICE_NAME 0x1003

#define AMBA_MSGID_GET_DEVICE_VERSION 0x1004

#define AMBA_MSGID_IS_SDCARD_MOUNTED 0x1101
#define AMBA_PARAM_SDCARD_MOUNTED_YES 1
#define AMBA_PARAM_SDCARD_MOUNTED_NO 0

#define AMBA_MSGID_IS_SDCARD_FULL 0x1102
#define AMBA_PARAM_SDCARD_FULL_NO 0
#define AMBA_PARAM_SDCARD_FULL_ALMOST 1
#define AMBA_PARAM_SDCARD_FULL_YES 2

#define AMBA_MSGID_SDCARD_SLOWLY_WRITE 0x1107
#define AMBA_MSGID_IS_SDCARD_NEED_FORMAT 0x1108
#define AMBA_PARAM_SDCARD_NEED_FORMAT_NO 0
#define AMBA_PARAM_SDCARD_NEED_FORMAT_YES 1

#define AMBA_MSGID_GET_BATTERY_VOLUME 0x1109
#define AMBA_PARAM_BATTERY_PERCENT5 0
#define AMBA_PARAM_BATTERY_PERCENT25 1
#define AMBA_PARAM_BATTERY_PERCENT50 2
#define AMBA_PARAM_BATTERY_PERCENT75 3
#define AMBA_PARAM_BATTERY_PERCENT100 4
#define AMBA_PARAM_BATTERY_CHARGE_FULL 0x44

#define AMBA_MSGID_GET_CAMERA_STATE 0x110A
//空闲
#define AMBA_PARAM_CAMERA_STATE_IDLE 0
#define AMBA_PARAM_CAMERA_STATE_STANDBY 1//待机
#define AMBA_PARAM_CAMERA_STATE_STORAGE 2//USB存储模式
#define AMBA_PARAM_CAMERA_STATE_CAPTURING 3//正在摄像
#define AMBA_PARAM_CAMERA_STATE_CAPTURING_MICRO 4//正在秒拍
#define AMBA_PARAM_CAMERA_STATE_CAPTURING_TIMELAPSE 5//正在延时摄像
#define AMBA_PARAM_CAMERA_STATE_PHOTOING 6//正在拍照
#define AMBA_PARAM_CAMERA_STATE_PHOTOING_DELAYED 7//定时拍照
#define AMBA_PARAM_CAMERA_STATE_PHOTOING_INTERVAL 12//间隔拍照
#define AMBA_PARAM_CAMERA_STATE_CAPTURING_SLOWMOTION 13//慢动作摄像
#define AMBA_PARAM_CAMERA_STATE_CAPTURING_CONTINUOUS 14//正在连续拍照

#define AMBA_MSGID_GET_CAMERA_ALL_PARAM 0x110B
#define AMBA_MSGID_GET_CAMERA_ALL_SETTING_PARAM 0x110C
#define AMBA_MSGID_GET_CAMERA_ALL_MODE_PARAM 0x110D

#define AMBA_MSGID_SET_VIDEO_RECORDING_SPEED 6402
#define AMBA_PARAM_VIDEO_RECORDING_SPEED_1X  1
#define AMBA_PARAM_VIDEO_RECORDING_SPEED_2X  2
#define AMBA_PARAM_VIDEO_RECORDING_SPEED_4X  4
#define AMBA_PARAM_VIDEO_RECORDING_SPEED_2D  130
#define AMBA_PARAM_VIDEO_RECORDING_SPEED_4D  132

#define AMBA_MSGID_SET_VIDEO_RECORDING_SPEED 6402

#define AMBA_MSGID_GET_MEDIA_INFO 1026

#define AMBA_MSGID_DELETE_FILE 1281

#define AMBA_MSGID_SET_WIFI_NEW 0x1602

#define AMBA_MSGID_DEFAULT_SETTINGS 0x1808///!!!
#define AMBA_MSGID_RESET_VENDOR_SETTINGS 0x1808

#define AMBA_MSGID_WAKEUP_CAMERA 0x180A
#define AMBA_MSGID_CLOSE_CAMERA  0x180B
#define AMBA_MSGID_CAMERA_OVERHEATED 0x180E
#define AMBA_MSGID_RECOVERY_MEDIA_FILE 0x1811
#define AMBA_MSGID_DELETE_FILES_DONE 0x1812

#define  AMBA_MSGID_SET_AUTO_SHUTDOWN_TIME 0x1807

#define  AMBA_MSGID_BEEPER_VOLUME 0x1801
#define  AMBA_PARAM_BEEPER_OFF 0
#define  AMBA_PARAM_BEEPER_VOLUME_25P 1
#define  AMBA_PARAM_BEEPER_VOLUME_50P 2
#define  AMBA_PARAM_BEEPER_VOLUME_75P 3
#define  AMBA_PARAM_BEEPER_VOLUME_100P 4

#define AMBA_MSGID_GET_STORAGE_TOTAL_FREE 5
#define AMBA_MSGID_GET_VIDEO_CAPACITY  0x1104
#define AMBA_MSGID_GET_PHOTO_CAPACITY  0x1105

#define AMBA_MSGID_RESET_DEFAULT_PARAMS  0x1809
#define AMBA_MSGID_RESET_DEFAULT_SETTINGS  0x1808

#define AMBA_MSGID_GET_STORAGE_ALL_STATE    (0x1106)

#define AMBA_RVAL_ERROR_INVALID_TOKEN (-4)
#define AMBA_RVAL_ERROR_INVALID_OPERATION (-14)
#define AMBA_RVAL_ERROR_SDCARD_FULL (-17)
#define AMBA_RVAL_ERROR_BUSY    (-21)
//    #define AMBA_RVAL_FORMAT_WITHOUT_SD    (-25)
#define AMBA_RVAL_ERROR_NO_SDCARD    (-50)
#define AMBA_RVAL_ERROR_WRONG_SDCARD    (-59)
#define AMBA_RVAL_ERROR_FAULT_SDCARD    (-61)
#define AMBA_RVAL_ERROR_WRONG_MODE    (-56)
#define AMBA_RVAL_ERROR_NO_FIRMWARE    (-57)
#define AMBA_RVAL_ERROR_SDCARD_FULL    (-17)
#define AMBA_RVAL_ERROR_LOW_BATTERY    (-58)
#define AMBA_RVAL_ERROR_INVALID_TOKEN    (-4)
#define AMBA_RVAL_ERROR_INVALID_OPERATION    (-14)
#define AMBA_RVAL_ERROR_INVALID_FILE_PATH    (-26)

#define AMBA_UPLOAD_FILE_TYPE_FW (1)
#define AMBA_UPLOAD_FILE_TYPE_RC_FW (2)

#define AMBA_MSGID_DOUYIN_WILL_STOP_CAPTURING 0x1901
//6401

#define AMBA_MSGID_SET_LENS_USAGE 6403
#define AMBA_PARAM_LENS_USAGE_LOGO 0
#define AMBA_PARAM_LENS_USAGE_LED  1
#define AMBA_PARAM_LENS_USAGE_BOTH 2

#define AMBA_MSGID_SET_VIDEO_SEGMENT_SECONDS 6404
#define AMBA_PARAM_VIDEO_SEGMENT_SECONDS_15 15
#define AMBA_PARAM_VIDEO_SEGMENT_SECONDS_30 30
#define AMBA_PARAM_VIDEO_SEGMENT_SECONDS_60 60
#define AMBA_PARAM_VIDEO_SEGMENT_SECONDS_300 300

#define AMBA_MSGID_SET_VIDEO_MBPS 6405
#define STRINGIZE0(...) __VA_ARGS__
#define STRINGIZE(...) #__VA_ARGS__
#define STRINGIZE2(...) STRINGIZE(__VA_ARGS__)
#define NSSTRINGIZE(...) @ STRINGIZE2(__VA_ARGS__)

#define HARDWARE_UPDATE_NAME  MadvSysFW.zip
#define REMOTER_UPDATE_NAME  rc_firmware.bin
#define HARDWARE_UPDATE_PATH  STRINGIZE2(/tmp/FL0/HARDWARE_UPDATE_NAME)
#define REMOTER_UPDATE_PATH  STRINGIZE2(/tmp/SD0/update/REMOTER_UPDATE_NAME)

// 0x1900
#define AMBA_MSGID_SET_CURRENT_APP_ID  6400
#define AMBA_PARAM_APP_ID_MADV 0
#define AMBA_PARAM_APP_ID_DOUYIN 2

#define AMBA_MSGID_DOUYIN_WILL_BEGIN_SHOOTING 6406

#endif /* AMBACommands_h */
